### ISSUE TITLE
Unable to use DartSassHost in local dotnet tool

### ISSUE THREAD

**Issue by sergeyzwezdin** [Taritsyn/DartSassHost#4]
DartSassHost crashed silently when trying to use it as part of the local `dotnet tool`.

Steps to reproduce:

1. Clone the sample project - https://github.com/sergeyzwezdin/dotnet-tool-DartSassHost/tree/master/dartsasshost-compiler
2. Open cloned project folder, build.
3. `dotnet pack dartsasshost-compiler.csproj`, save the path where is a package created, for example:

>  Successfully created package '/Users/sergeyzwezdin/Temp/dotnet-tool-DartSassHost/dartsasshost-compiler/bin/Debug/dartsasshost-compiler.1.0.0.nupkg'.

In this example we need `/Users/sergeyzwezdin/Temp/dotnet-tool-DartSassHost/dartsasshost-compiler/bin/Debug/`

4. Create a new directory somewhere else, the next steps should be run from there:
5. `dotnet new tool-manifest`
6. `dotnet tool install dartsasshost-compiler --version 1.0.0 --add-source=/Users/sergeyzwezdin/Temp/dotnet-tool-DartSassHost/dartsasshost-compiler/bin/Debug/` < replace path here
7. Put some `test.scss` file into the directory
8. `dotnet tool run dartsasshost-compiler test.scss`

Normally, this should return compiled code like this:
![2022-01-09 at 23 08 03](https://user-images.githubusercontent.com/800755/148694716-711dcfe7-b22a-4876-aaaf-a0407df47633.png)

But if we use it as a local dotnet tool it will fail silently and nothing is displayed:
![2022-01-09 at 23 08 49](https://user-images.githubusercontent.com/800755/148694739-1927d2db-a531-40a8-bab4-a5f7918e8c91.png)

Also, it is interesting that it works okay if we install the tool globally. 🤔

**Comment by Taritsyn** [comment]
Hello, Sergey!

I have tested your package on different operating systems.

On Windows 10 (x64) everything works:

![windows-10-x64](https://user-images.githubusercontent.com/251859/148784570-c0804826-9979-49cf-9202-1673b498bf12.png)

On Ubuntu 20.04 (x64) everything works too:

![ubuntu-20 04-x64](https://user-images.githubusercontent.com/251859/148784800-babdb3c4-3489-4b1e-b08f-2a02845bb352.png)

A [well-known bug](https://github.com/microsoft/ClearScript/issues/333) did not allow testing on macOs 10.13. But I rebuilt your package with a dependency on the  JavaScriptEngineSwitcher.Jint version 3.16.0 Preview (works correctly only under .NET 5+) instead of the JavaScriptEngineSwitcher.V8, and everything works too:

![macos-10 13-x64](https://user-images.githubusercontent.com/251859/148786648-33443434-de8c-48d3-8ed3-220799a8e7ee.png)

Unfortunately, it  is no possibility yet to test the package on macOs 12.

**Comment by sergeyzwezdin** [comment]
Hello Andrey!
Thank you for your explanation. Does it mean that WebCompiler should you Jint instead of V8?

**Comment by Taritsyn** [comment]
For now, I recommend you to check how the [Excubo.WebCompiler version 3.0.1 Preview 2](https://www.nuget.org/packages/Excubo.WebCompiler/3.0.1-preview.2) works on macOS 12.1.

**Comment by sergeyzwezdin** [comment]
@Taritsyn the same result with `3.0.1-preview.2` - just crashes silently

![2022-01-10 at 21 28 50](https://user-images.githubusercontent.com/800755/148801749-03dd8e63-90b1-4117-8a44-76a410aaee6b.png)

**Comment by Taritsyn** [comment]
Then I recommend that you try to build your own package based on Jint.

**Comment by sergeyzwezdin** [comment]
So, is that right that it is not going to be fixed?

**Comment by Taritsyn** [comment]
Must first understand whether the modification with Jint works on your machine.

**Comment by Taritsyn** [comment]
Can you show me the contents of `test.scss` file?

**Comment by sergeyzwezdin** [comment]
```
.test { color: red; }
```

**Comment by Taritsyn** [comment]
It's good that it's not empty ;-) With an empty file, this error is reproduced completely:

![windows-10-x64-empty](https://user-images.githubusercontent.com/251859/148809686-a0905617-f2f4-4455-8b9e-996d39728f42.png)

In general, what's stopping you from using the [Node.js-version of this tool](https://www.npmjs.com/package/sass) from Google?

**Comment by sergeyzwezdin** [comment]
> In general, what's stopping you from using the Node.js-version of this tool from Google?

In general, the team does not want to install Node tool to be able to build the project, but if it won't work that's the still option.

**Comment by Taritsyn** [comment]
Hello, Sergey!

Today I had the opportunity to run your original example on macOS 12.1 (x64). The error was reproduced, but under certain conditions.

The error reproduces well on a clean operating system with the [.NET 6.0.101 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-macos-x64-installer) installed:

![before-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149631763-98634404-ce09-487b-8d5f-3b7eacb899a0.png)

If install the [.NET 5.0.13 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-5.0.13-macos-x64-installer), then this error no longer occurs:

![after-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149631911-a2c820a1-cc17-4ed9-bea6-a9c8ea8096ce.png)

But it happens because .NET perceives the operating system as macOS 11, although the operating system itself has not changed:

![about-this-mac](https://user-images.githubusercontent.com/251859/149632069-417f07c6-8342-4f57-96fa-0694c735b6bb.png)

**Comment by sergeyzwezdin** [comment]
@Taritsyn thank you for your investigation. Do you think that the problem is .NET itself, not DartSassHost?
.NET 5 is not an option since the requirement is to run SASS compilation on Apple Silicone as well.
But anyway, we're going to use a native node to build the assets, so it's up to you to continue the issue investigation.

**Comment by Taritsyn** [comment]
Hello, Sergey!

Apparently, this error occurs at the Microsoft ClearScript.V8 library level, because when using the JavaScriptEngineSwitcher.ChakraCore and JavaScriptEngineSwitcher.Jint modules everything works correctly.

Now I am trying to reproduce this error without using the DartSassHost library.

**Comment by Taritsyn** [comment]
It seems that the [“Net 6 test runners support”](https://github.com/microsoft/ClearScript/issues/318) issue and this error have the same reason.

If modify your example as follows:

**dartsasshost-compiler.csproj**

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>dartsasshost_compiler</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dartsasshost-compiler</ToolCommandName>
    <AssemblyName>dartsasshost-compiler</AssemblyName>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x86" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-arm64" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.linux-x64" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.linux-arm" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.linux-arm64" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.osx-x64" Version="7.2.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.osx-arm64" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="package.csproj" />
  </ItemGroup>

</Project>
```

**Program.cs**

```csharp
using Microsoft.ClearScript.V8;

using (var engine = new V8ScriptEngine())
{
    Console.WriteLine("Start script execution...");

    engine.Execute(@"var count = 0;

for (var i = 1; i < 1000000; i++) {
    count++;
}"
    );
    var count = (int)engine.Evaluate("count");

    Console.WriteLine("Number of iterations: {0}", count);
}
```

Then with a clean installation of the [.NET 6.0.101 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-macos-x64-installer) we will get a similar error:

![before-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149815316-100395ac-0b07-4769-bed3-feb96c21da0a.png)

And if the [.NET 5.0.13 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-5.0.13-macos-x64-installer) is also installed, the result will be correct:

![after-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149816003-ab6d1776-488d-4d90-9c04-c3d451dda002.png)
