### ISSUE TITLE
Non-preview / prod ready release

### ISSUE THREAD

**Issue by deanwiseman** [Taritsyn/DartSassHost#5]
Hi Taritsyn,

Are you planning a non-preview release of this library at some point in time?

`DartSassBuilder` has a dependency on your package's `v1.0.0-preview7` and was wondering when we could look at a full release

Thanks

**Comment by Taritsyn** [comment]
Hello, Dean!

Unfortunately, I cannot give an exact date, because now I have little free time due to participation in the the [competition of open source projects](https://github.com/Taritsyn/WebMarkupMin/issues/137). Besides, not all functionality of the Dart Sass Host library is stable yet.

So far, I'm planning a release for mid-April.

**Comment by deanwiseman** [comment]
Understood. Thanks for the info!

**Comment by Taritsyn** [comment]
Hello, Dean!

[First stable release](https://github.com/Taritsyn/DartSassHost/releases/tag/v1.0.0) was released yesterday.
