### ISSUE TITLE
Use sass-embedded instead of dart-sass.js

### ISSUE THREAD

**Issue by joneff** [Taritsyn/DartSassHost#7]
For a while now, there is a [dart-sass-embedded](https://github.com/sass/dart-sass-embedded) that is, for the lack of a better word, faster, when compared to dart-sass.js. (I realize that at the start of the project, native dart binaries were not available and dart-sass.js was used for that reason.)

There is a [node integration example](https://github.com/sass/embedded-host-node) that's actually the sass-embedded npm package. It should give an idea how the recommended way, using embedded sass protocol, should work... it node environment that is.

**Comment by Taritsyn** [comment]
Hello, Ivan!

As far as I understand, there is already a libraries using this approach: [Citizen17.DartSass](https://github.com/Vampire2008/Citizen17.DartSass) and [AspNetCore.SassCompiler](https://github.com/koenvzeijl/AspNetCore.SassCompiler).

I myself do not plan to use this approach, because I am interested in working with the JS version of Dart Sass.
